'use strict';
(() => {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toys=[['peach','복숭아 퉁퉁이','왼쪽 눈만 깨어난 복숭아'],['pudding','카라멜 멍푸딩','체리 모자 쓴 멍한 푸딩'],['cloud','구름 퉁구리','비 오기 직전의 표정'],['cat','냐옹 감자','한쪽 귀만 열심인 고양이'],['mochi','딸기 덜렁이','모자가 조금 큰 딸기떡']];
const parts=[['peach','🍑','복숭아 조각','fruit','pop'],['strawberry','🍓','딸기 모자','fruit','pop'],['cherry','🍒','체리 안테나','fruit','pop'],['heart','🪤','이상한 하트','cute','pop'],['star','🧷','안전핀 별','cute','crunch'],['flower','🪰','날파리','cute','crunch'],['bear','🪨','작은 돌','cute','crunch'],['ribbon','🧦','잃어버린 양말','cute','crunch'],['bubble','🫧','수상한 기포','bead','glass'],['pearl','🟤','콩알','bead','glass'],['gem','🧊','얼음 조각','bead','glass'],['candy','🧄','마늘 사탕','bead','crunch']];
const modes={tap:['톡 누르기','말랑이를 가볍게 톡! 누르면 파츠가 통통 튀어요.','톡! ♡'],hold:['길게 누르기','꾹 누르고 기다려봐요. 힘을 빼면 다시 말랑~','꾸우욱~'],rub:['문지르기','누른 채 좌우로 움직이면 파츠가 사르르 섞여요.','조물조물 ♡'],rapid:['연속 터치','빠르게 톡톡! 누를수록 바스락 소리가 나요.','바스락!']};
const state={toy:0,step:1,mode:'tap',count:0,sound:true,volume:.55,selected:['peach','heart','star','bubble','flower','heart','pearl','ribbon','star','bubble','peach','gem'],particles:[],down:false,x:400,y:400,press:0,vpress:0,shift:0,shiftV:0,held:0,emotion:0,lastTap:0,lastSound:0,filter:'all',ready:false};
const canvas=$('#toy'),screen=canvas.getContext('2d'),skin=document.createElement('canvas');skin.width=800;skin.height=720;const ctx=skin.getContext('2d'),soft=new SoftBody(),softRenderer=new SoftRenderer(soft); const art=toys.map(t=>{const im=new Image();im.src=window.MALLANG_ART?.[t[0]]||`assets/toys/${t[0]}.png`;return im});
let audioCtx,master,buffers={},audioInit,voices=0,audioFailed=false;
async function initAudio(){if(audioInit)return audioInit;audioInit=(async()=>{try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=state.sound?state.volume:0;master.connect(audioCtx.destination);await Promise.all(Object.entries(window.MALLANG_SOUNDS||{}).map(async([key,b64])=>{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));buffers[key]=await audioCtx.decodeAudioData(bytes.buffer)}));}catch(e){audioFailed=true;$('#part-status').textContent='이 브라우저에서는 소리를 재생할 수 없어요.';}})();return audioInit;}
async function sound(kind='crunch',force=.7){if(!state.sound||state.volume===0)return;await initAudio();if(!audioCtx||audioFailed)return;try{if(audioCtx.state==='suspended')await audioCtx.resume();if(!buffers[kind]||voices>=8)return;const src=audioCtx.createBufferSource(),gain=audioCtx.createGain();src.buffer=buffers[kind];src.playbackRate.value=.86+Math.random()*.28;gain.gain.value=Math.min(1,force)*.48;src.connect(gain);gain.connect(master);voices++;src.onended=()=>{voices--;src.disconnect();gain.disconnect()};src.start();}catch(e){audioFailed=true;}}
function part(id){return parts.find(p=>p[0]===id)}
function setToy(i){soft.clear();state.down=false;state.toy=i;$('#toy-name').textContent=toys[i][1];renderToys();state.emotion=20;refreshRecipe();}
function renderToys(){$('#toy-options').innerHTML=toys.map((t,i)=>`<button class="toy-card ${i===state.toy?'selected':''}" data-toy="${i}" aria-pressed="${i===state.toy}"><img src="assets/toys/${t[0]}.png" alt="">${i===state.toy?'<span class="check">✓</span>':''}<strong>${t[1]}</strong><small>${t[2]}</small></button>`).join('');$$('[data-toy]').forEach(b=>b.onclick=()=>setToy(+b.dataset.toy));}
function renderParts(){$('#part-options').innerHTML=parts.filter(p=>state.filter==='all'||p[3]===state.filter).map(p=>`<button class="part-card" data-part="${p[0]}" aria-label="${p[2]} 넣기"><span>${p[1]}</span><small>${p[2]}</small></button>`).join('');$$('[data-part]').forEach(b=>b.onclick=()=>{if(state.selected.length>=24){$('#part-status').textContent='24개가 꽉 찼어요! 파츠를 빼고 넣어주세요.';return;}state.selected.push(b.dataset.part);addParticle(b.dataset.part);renderBasket();sound(part(b.dataset.part)[4],.4);});}
function addParticle(id){state.particles.push({id,x:(Math.random()-.5)*290,y:25+Math.random()*105,vx:(Math.random()-.5)*4,vy:-3-Math.random()*3,r:19+Math.random()*8,a:(Math.random()-.5)*.35,spin:0});}
function resetParticles(){state.particles=[];state.selected.forEach(addParticle)}
function renderBasket(){$('#part-count').textContent=`${state.selected.length} / 24`;$('#basket').innerHTML=state.selected.map((id,i)=>`<button data-remove="${i}" aria-label="${part(id)[2]} 빼기">${part(id)[1]}</button>`).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{state.selected.splice(+b.dataset.remove,1);state.particles.splice(+b.dataset.remove,1);renderBasket()});$('#part-status').textContent='넣은 파츠를 누르면 뺄 수 있어요.';refreshRecipe();}
function refreshRecipe(){$('#recipe-name').textContent=toys[state.toy][1];$('#recipe-parts').textContent=state.selected.map(id=>part(id)[1]).join(' ')||'파츠 없이도 보들보들 ♡';}
function step(n){state.step=n;$$('.step').forEach((el,i)=>el.hidden=i!==n-1);$$('[data-step]').forEach(b=>{b.classList.toggle('active',+b.dataset.step===n);if(+b.dataset.step===n)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});if(n===3){refreshRecipe();$('#bubble').textContent='놀 준비 완료 ♡';} }
function mode(m){state.mode=m;$$('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===m);b.setAttribute('aria-pressed',b.dataset.mode===m)});$('#gesture-label').textContent=modes[m][0];$('#gesture-help').textContent=modes[m][1];}
function point(e){const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left)/b.width*800,y:(e.clientY-b.top)/b.height*720}}
function hit(p){return ((p.x-400)/275)**2+((p.y-410)/230)**2<1.08}
function bump(x,y,force){for(const p of state.particles){const dx=p.x-(x-400),dy=p.y-(y-425),d=Math.hypot(dx,dy)||1;const f=Math.max(.4,1-d/440)*force;p.vx+=dx/d*f+(Math.random()-.5)*2;p.vy+=dy/d*f-2.5;p.spin=(Math.random()-.5)*.09;}}
function interact(x,y){const now=performance.now();state.count++;$('#count').textContent=state.count;state.x=x;state.y=y;state.down=true;state.held=0;state.emotion=1;state.vpress+=.027;const rapid=now-state.lastTap<330||state.mode==='rapid';state.lastTap=now;$('#bubble').textContent=rapid?'바스락!':modes[state.mode][2];bump(x,y,rapid?14:8);sound(rapid?'crunch':(state.selected.length?part(state.selected[Math.floor(Math.random()*state.selected.length)])[4]:'squish'),.8);sound('squish',.3);state.lastSound=now;}
function release(){state.down=false;state.vpress-=.012;state.emotion=60;}
let keyboard=false;
canvas.addEventListener('pointerdown',e=>{const p=point(e);if(!hit(p)&&!soft.grips.size)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);soft.grab(e.pointerId,p.x,p.y,e.pressure||.5);interact(p.x,p.y);});
canvas.addEventListener('pointermove',e=>{if(!soft.grips.has(e.pointerId))return;const p=point(e),g=soft.grips.get(e.pointerId);const dx=Math.max(-30,Math.min(30,p.x-g.x)),dy=Math.max(-30,Math.min(30,p.y-g.y));soft.move(e.pointerId,p.x,p.y,e.pressure||.5);state.x=p.x;state.y=p.y;const dist=Math.hypot(dx,dy);if(dist>1){for(const c of state.particles){c.vx+=dx*.19;c.vy+=dy*.16-.4;}state.emotion=1;$('#bubble').textContent=Math.hypot(p.x-g.ax,p.y-g.ay)>85?'쭈우욱~':'조물조물 ♡';if(performance.now()-state.lastSound>105){sound(state.selected.length?part(state.selected[Math.floor(Math.random()*state.selected.length)])[4]:'squish',Math.min(.8,dist/15));state.lastSound=performance.now();}}});
function endPointer(e){if(!soft.grips.has(e.pointerId))return;soft.release(e.pointerId);if(!soft.grips.size){release();$('#bubble').textContent='말랑~ 탱글!';bump(state.x,state.y,5);}}
canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);canvas.addEventListener('lostpointercapture',endPointer);
canvas.addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='Enter')&&!e.repeat){e.preventDefault();keyboard=true;soft.grab('keyboard',400,340);interact(400,340)}});
canvas.addEventListener('keyup',e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();keyboard=false;soft.release('keyboard');if(!soft.grips.size)release()}});
canvas.addEventListener('blur',()=>{if(keyboard){keyboard=false;soft.release('keyboard');if(!soft.grips.size)release()}});
window.addEventListener('blur',()=>{soft.clear();keyboard=false;release()});
let lastFrame=0,frame=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
function draw(time){const dt=Math.min(2,(time-lastFrame)/16.667||1);lastFrame=time;frame++;if(state.down){state.held+=dt;if(state.held>26&&time-state.lastSound>210){sound(state.selected.length?'crunch':'squish',.36);state.lastSound=time;if([...soft.grips.values()].every(g=>Math.hypot(g.x-g.ax,g.y-g.ay)<45))$('#bubble').textContent='꾸우욱~';bump(state.x,state.y,1.2);}}else if(state.emotion>0)state.emotion-=dt;
 const target=state.down?Math.min(.21,.095+state.held*.0008):0;state.vpress+=(target-state.press)*.12*dt;state.vpress*=Math.pow(.72,dt);state.press+=state.vpress*dt;state.shiftV+=-state.shift*.075*dt;state.shiftV*=Math.pow(.79,dt);state.shift+=state.shiftV*dt;
 for(let i=0;i<state.particles.length;i++){const p=state.particles[i];p.vy+=.12*dt;p.vx*=Math.pow(.975,dt);p.vy*=Math.pow(.977,dt);p.x+=p.vx*dt;p.y+=p.vy*dt;p.a+=p.spin*dt;p.spin*=.97;const bound=188*Math.sqrt(Math.max(.15,1-((p.y-30)/170)**2));if(Math.abs(p.x)>bound-p.r*.35){p.x=Math.sign(p.x)*(bound-p.r*.35);p.vx*=-.65}if(p.y>155-p.r*.6){p.y=155-p.r*.6;p.vy=-Math.abs(p.vy)*.55;p.vx*=.98}if(p.y<-100){p.y=-100;p.vy=Math.abs(p.vy)*.6}for(let j=i+1;j<state.particles.length;j++){const q=state.particles[j],dx=q.x-p.x,dy=q.y-p.y,d=Math.hypot(dx,dy)||1,min=(p.r+q.r)*.65;if(d<min){const f=(min-d)*.18;p.x-=dx/d*f;p.y-=dy/d*f;q.x+=dx/d*f;q.y+=dy/d*f;p.vx-=dx/d*f*.18;q.vx+=dx/d*f*.18;}}}
 soft.step(dt,reduce);render(time);requestAnimationFrame(draw);}
function render(time){ctx.clearRect(0,0,800,720);ctx.save();
 const im=art[state.toy];if(im.complete&&im.naturalWidth){const ratio=im.naturalWidth/im.naturalHeight;const h=Math.min(465,560/ratio),w=h*ratio;ctx.drawImage(im,400-w/2,610-h,w,h);}
 ctx.save();ctx.beginPath();ctx.ellipse(400,456,211,143,0,0,Math.PI*2);ctx.clip();for(const p of state.particles){ctx.save();ctx.translate(400+p.x,425+p.y);ctx.rotate(p.a);ctx.globalAlpha=.86;ctx.font=`${p.r*1.8}px "Segoe UI Emoji","Apple Color Emoji",sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='#bc617c30';ctx.shadowBlur=4;ctx.fillText(part(p.id)[1],0,0);ctx.restore()}const sheen=ctx.createLinearGradient(240,340,550,590);sheen.addColorStop(0,'#ffffff45');sheen.addColorStop(.5,'#ffffff00');sheen.addColorStop(1,'#ffffff33');ctx.fillStyle=sheen;ctx.fillRect(160,310,480,310);ctx.restore();
 for(const g of soft.grips.values()){
   const radius=67,shade=ctx.createRadialGradient(g.ax,g.ay,5,g.ax,g.ay,radius);
   shade.addColorStop(0,'#8e446c35');shade.addColorStop(.45,'#a5647923');shade.addColorStop(.72,'#fff6ee08');shade.addColorStop(.84,'#fff6ee95');shade.addColorStop(1,'#ffffff00');ctx.fillStyle=shade;ctx.beginPath();ctx.ellipse(g.ax,g.ay,radius,radius*.8,0,0,Math.PI*2);ctx.fill();
 }
 ctx.restore();screen.clearRect(0,0,800,720);const sh=screen.createRadialGradient(400,615,10,400,615,260);sh.addColorStop(0,'#b9687138');sh.addColorStop(1,'#b9687100');screen.fillStyle=sh;screen.beginPath();screen.ellipse(400,615,260,30,0,0,Math.PI*2);screen.fill();screen.drawImage(softRenderer.draw(skin),0,0);
}
$$('[data-next]').forEach(b=>b.onclick=()=>step(+b.dataset.next));$$('[data-step]').forEach(b=>b.onclick=()=>step(+b.dataset.step));$$('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderParts()});
$('#clear').onclick=()=>{state.selected=[];resetParticles();renderBasket()};$('#random').onclick=()=>{state.selected=Array.from({length:15},()=>parts[Math.floor(Math.random()*parts.length)][0]);resetParticles();renderBasket();sound('glass',.5)};
$('#sound').onclick=()=>{state.sound=!state.sound;$('#sound').setAttribute('aria-pressed',state.sound);$('#sound span').textContent=state.sound?'소리 켜짐':'소리 꺼짐';if(master)master.gain.value=state.sound?state.volume:0;if(state.sound)sound('pop',.4)};$('#volume').oninput=e=>{state.volume=+e.target.value/100;$('#volume-value').textContent=`${e.target.value}%`;if(master)master.gain.value=state.sound?state.volume:0};
$('#save').onclick=async()=>{try{await Promise.all(art.map(im=>im.decode()));const out=document.createElement('canvas');out.width=1000;out.height=1080;const c=out.getContext('2d');const g=c.createLinearGradient(0,0,1000,1080);g.addColorStop(0,'#e2f2ff');g.addColorStop(.65,'#fff0f1');g.addColorStop(1,'#ffdbe6');c.fillStyle=g;c.fillRect(0,0,1000,1080);c.textAlign='center';c.fillStyle='#74434a';c.font='bold 28px "Malgun Gothic",sans-serif';c.fillText('J LAB · 말랑이 연구소',500,93);c.font='bold 45px "Malgun Gothic",sans-serif';c.fillText(toys[state.toy][1],500,171);render(performance.now());c.drawImage(canvas,50,160,900,810);c.font='23px "Malgun Gothic",sans-serif';c.fillText('내가 좋아하는 것들로 채운, 나만의 말랑이 ♡',500,1000);const link=document.createElement('a');link.download=`말랑이-${toys[state.toy][0]}.png`;link.href=out.toDataURL('image/png');link.click();}catch(e){$('#bubble').textContent='이미지 저장을 다시 시도해 주세요';}};
try{document.modelContext?.registerTool({name:'configure_squishy',title:'말랑이 꾸미기',description:'말랑이 종류와 파츠를 선택하고 조물조물 단계로 이동합니다.',inputSchema:{type:'object',properties:{toy:{type:'string',enum:toys.map(t=>t[0])},parts:{type:'array',items:{type:'string',enum:parts.map(p=>p[0])},maxItems:24}},required:['toy','parts'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!toys.some(t=>t[0]===input.toy)||!Array.isArray(input.parts)||input.parts.length>24||input.parts.some(id=>!part(id)))throw new Error('잘못된 말랑이 또는 파츠입니다.');setToy(toys.findIndex(t=>t[0]===input.toy));state.selected=[...input.parts];resetParticles();renderBasket();step(3);return {toy:input.toy,parts:[...state.selected],step:3}}})?.catch?.(()=>{});}catch(e){}
renderToys();renderParts();resetParticles();renderBasket();requestAnimationFrame(draw);
})();
